---
name: Python checks
on:
  push:
    paths:
      - 'src/**'
      - 'tests/**'

jobs:
  python-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version-file: '.python-version'
      - name: Install dependencies
        run: python -m pip install -r requirements-dev.txt
      - name: Run
        run: pre-commit run -a python --show-diff-on-failure

