---
name: Terraform Checks
on:
  push:
    paths:
      - 'infra/terraform/**'

jobs:
  terraform-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Terraform Version
        id: set_tf_version
        run: echo "tf_version=$(cat .terraform-version)" >> $GITHUB_OUTPUT
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ steps.set_tf_version.outputs.tf_version }}
      - name: Run
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
          pre-commit run -a terraform
